# Site settings

title: Andrew Ba Tran # Title of your site
email: abtran@gmail.com # Your contant email

description: Portfolio site
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://abtran2.github.io" # the base hostname & protocol for your site

# Social links.
# Replace the word 'example' with your username if you want to include the icon in the left sidebar
# Delete the word 'example' if you don't want to include the icon in the left sidebar

twitter_username:     abtran  # Replace this with your Twitter username
github_username:      andrewbtran  # Replace this with your GitHub username
linkedin_username:    abtran  # Replace this with your LinkedIn username
facebook_username:    abtran # Replace this with your Facebook username

# Build settings
markdown: kramdown
